//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLend.Data.Resources.Reservation {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoLend.Data.Resources.Reservation.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DECLARE @CustomerId CHAR(36) = (
        ///	SELECT 
        ///		[Id] 
        ///	FROM 
        ///		[dbo].[Customers] 
        ///	WHERE 
        ///			[FirstName] = @FirstName 
        ///		AND [LastName] = @LastName 
        ///		AND [Email] = @Email
        ///		AND [IsActive] = 1
        ///	)
        ///
        ///DECLARE @CarId INT = (
        ///	SELECT 
        ///		[Id] 
        ///	FROM 
        ///		[dbo].[Cars] 
        ///	WHERE 
        ///		[LicensePlate] = @LicensePlate
        ///	AND [IsActive] = 1
        ///	)
        ///
        ///DECLARE @StatusId INT = (
        ///	SELECT 
        ///		[Id] 
        ///	FROM 
        ///		[dbo].[Status] 
        ///	WHERE 
        ///			[StatusName] = &apos;Confirmed&apos;
        /// 		AND [IsActive] = 1
        ///	)
        ///
        ///INSERT INTO dbo.Reservation [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Reservation_Create {
            get {
                return ResourceManager.GetString("Reservation_Create", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu UPDATE 
        ///	[dbo].[Reservations]
        ///SET 
        ///	[ModifyDate] = GETDATE(),
        ///	[IsActive] = 0
        ///WHERE 
        ///	[Id] = @reservationId 
        ///AND [IsActive] = 1;
        ///.
        /// </summary>
        internal static string Reservation_Delete {
            get {
                return ResourceManager.GetString("Reservation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu -- File: Reservation_GetAll.sql
        ///
        ///SELECT 
        ///	[R].[Id], 
        ///	[R].[CreateDate], 
        ///	[R].[ModifyDate], 
        ///	[R].[ReservationFrom], 
        ///	[R].[ReservationTo], 
        ///	[R].[Description], 
        ///	[S].[StatusName],
        ///	[B].[BrandName], 
        ///	[M].[ModelName], 
        ///	[CA].[LicensePlate], 
        ///	[CU].[FirstName], 
        ///	[CU].[LastName], 
        ///	[CU].[Email] 
        ///
        ///FROM [dbo].[Reservations]		AS [R]	
        ///INNER JOIN [dbo].[Status]		AS [S]	ON [R].StatusId = [S].[Id]
        ///INNER JOIN [dbo].[Cars]			AS [CA]	ON [R].CarId = [CA].[Id]
        ///INNER JOIN [dbo].[Customers]	AS [CU]	ON  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Reservation_GetAll {
            get {
                return ResourceManager.GetString("Reservation_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT 
        ///    [R].[Id], 
        ///    [R].[CreateDate], 
        ///    [R].[ModifyDate], 
        ///    [R].[ReservationFrom], 
        ///    [R].[ReservationTo], 
        ///    [R].[Description], 
        ///    [S].[StatusName],
        ///    [B].[BrandName], 
        ///    [M].[ModelName], 
        ///    [CA].[LicensePlate], 
        ///    [CU].[FirstName], 
        ///    [CU].[LastName], 
        ///    [CU].[Email] 
        ///
        ///FROM [dbo].[Reservations] AS [R]
        ///INNER JOIN [dbo].[Status] AS [S] ON [R].StatusId = [S].[Id]
        ///INNER JOIN [dbo].[Cars] AS [CA] ON [R].CarId = [CA].[Id]
        ///INNER JOIN [dbo].[Customers] AS [CU] ON [ [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Reservation_GetById {
            get {
                return ResourceManager.GetString("Reservation_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu UPDATE [R]
        ///SET 
        ///	[R].[ReservationFrom] = @ReservationFrom,
        ///	[R].[ReservationTo] = @ReservationTo,
        ///	[R].[Descriptions] = @Descriptions
        ///FROM [dbo].[Reservations] AS [R]
        ///WHERE 
        ///		[R].[Id] = @Id
        ///	AND [R].[IsActive] = 1;.
        /// </summary>
        internal static string Reservation_Update {
            get {
                return ResourceManager.GetString("Reservation_Update", resourceCulture);
            }
        }
    }
}
